[package]
name = "arkcursor"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "ArkCursor"
path = "src/main.rs"

[dependencies]
eframe = "0.29"
egui = "0.29"
rfd = "0.15"
image = { version = "0.25", default-features = false, features = ["png", "ico"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
log = "0.4"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Console",
    "Win32_Security",
    "Win32_System_Registry",
] }

[profile.release]
opt-level = 2
lto = true
